- name: Scan host keys
  delegate_to: localhost
  ansible.builtin.command:
    cmd: "xargs -n1 ssh-keyscan 2> /dev/null"
    stdin: "{{ inventory_hostname }} {{ ansible_host }}"
  register: keyscan_output

- name: Register scanned keys as fact
  delegate_to: localhost
  ansible.builtin.set_fact:
    host_keys: "{{ keyscan_output.stdout_lines }}"

- name: Gather all keys
  delegate_to: localhost
  run_once: yes
  ansible.builtin.set_fact:
    new_ssh_host_keys: "{{ hostvars | dict2items | selectattr('key', 'in', ansible_play_hosts) | map(attribute='value') | map(attribute='host_keys') | flatten }}"

- name: Remove old host keys on controller
  delegate_to: localhost
  run_once: yes
  ansible.builtin.known_hosts:
    state: absent
    path: "{{ known_hosts_file }}"
    hash_host: "{{ known_hosts_hash_host }}" 
    name: "{{ item.split(' ', 1).0 }}"
  loop: "{{ new_ssh_host_keys }}"

- name: Install host keys on controller
  delegate_to: localhost
  run_once: yes
  ansible.builtin.known_hosts:
    state: present
    path: "{{ known_hosts_file }}"
    hash_host: "{{ known_hosts_hash_host }}" 
    name: "{{ item.split(' ', 1).0 }}"
    key: "{{ item }}"
  loop: "{{ new_ssh_host_keys }}"

