- name: Deploy machine in MAAS
  delegate_to: localhost
  heilerich.maas.deploy:
    system_id: "{{ maas_id }}"
    wait: True
    wait_interval: "{{ deployment_poll_interval }}"
    wait_timeout: "{{ deployment_wait_interval }}"
    user_data: "{{ machine_user_data | b64encode }}"
  register: deployment_result

- name: Give MAAS time to update it's data 
  delegate_to: localhost
  run_once: yes
  ansible.builtin.wait_for:
    timeout: 10

- meta: refresh_inventory

- name: SSH Keyscan
  import_tasks: keyscan.yml
  tags: keyscan

- name: Wait for host to become available
  ansible.builtin.wait_for_connection:
    timeout: 900

- name: Gather facts
  setup:

- name: Install snap
  become: yes
  ansible.builtin.command:
    cmd: "snap install lxd --channel '{{ lxd_snap_channel }}'"
  register: snap_install
  changed_when: "'already installed' not in snap_install.stderr"
- name: Refresh snap
  become: yes
  ansible.builtin.command:
    cmd: "snap refresh lxd --channel '{{ lxd_snap_channel }}'"
  register: snap_refresh
  changed_when: "'has no updates' not in snap_refresh.stderr"
  when: "not snap_install.changed"

- name: Get current LXD configuration
  ansible.builtin.command:
    cmd: "/snap/bin/lxd init --dump"
  register: lxd_init_pre_dump
  changed_when: False

- name: Configure LXD
  vars:
    preseed: "{{ lookup('template', lookup('vars', 'lxd_preseed_file', default='lxd_preseed.yml.j2')) }}"
  ansible.builtin.shell:
    cmd: "/snap/bin/lxd init --preseed && /snap/bin/lxd init --dump"
    stdin: "{{ preseed }}"
  register: lxd_init_post_dump
  changed_when: "(lxd_init_post_dump.stdout|from_yaml|to_json) != (lxd_init_pre_dump.stdout|from_yaml|to_json)"

- name: Get existings VM hosts
  heilerich.maas.api_call:
    endpoint: "pods/"
    method: "GET"
  register: existing_vm_hosts

- name: Register VM host with MAAS
  include_tasks: register.yml
  when: "inventory_hostname not in existing_vm_hosts.data|map(attribute='name')"

