machine_user_data: |
  #cloud-config
  package_upgrade: true
  ssh_pwauth: no

deployment_poll_interval: 20
deployment_wait_interval: 900

# If you do not supply host keys in deployment user data the host
# key will have changed after deployment. To automatically update
# your local known_hosts file set this to true.
update_ssh_host_key: false

# The location of the known hosts file on the control node
known_hosts_file: "~/.ssh/known_hosts"
known_hosts_hash_host: false

# You have to options when deploying the hosts regarding the SSH host
# keys. 
# (1) You let ansible generate host keys on the controller, 
# install the private keys with the user data when deployin and then
# install the public keys on the controller. This is the default 
# behaviour and requires that you trust your controller with the host
# keys.
# (2) You let the deployed host generate new host keys for itself and
# then install the public keys on the controller using ssh-keyscan after
# deployment. In this case the host keys never leave the host, but
# you are potentially vulnerable to a MITM attack when scanning the
# new host keys for the first time.
generate_ssh_keys_on_host: false

# Set machine FQDN used in MAAS to connect to the LXD API
# If none, uses ansible_host
# machine_fqdn: vm_host.example.com

lxd_snap_channel: "latest/stable"
lxd_listen_port: "8443"
lxd_bridge_interface: "br0"

# The role will generate a random trust password for MAAS to register
# with the LXD API and then removes that password. If LXD has already
# been configured with a password, the deployment fails unless you
# set lxd_override_trust_password to true. In that case the existing
# password will be overriden and then removed.
lxd_override_trust_password: false

# LXD will be initialised with dir storage at the default location.
# If you want to use custom settings you can provide a custom preseed
# with the lxd_preseed_file variable. Please make sure to include the
# port variable, otherwise setting up the connection to MAAS will fail.
# lxd_preseed_file: mycustomseed.yml.j2

# The resource pool and zone to add the new vm host to
vm_host_pool: "default"
vm_host_zone: "default"
